<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>cloud.bytepulse</groupId>
    <artifactId>bp</artifactId>
    <version>0.0.1</version>
    <name>bp</name>
    <description>
        企业级 Spring Boot 通用开发框架，集成认证授权、日志追踪、文件存储、第三方接口认证等核心能力
    </description>
    <url>https://gitee.com/byte-pulse/bp</url>
    <licenses>
        <license>
            <name>MIT License</name>
            <url>https://opensource.org/licenses/MIT</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <developers>
        <developer>
            <id>jiejiebiezheyang</id>
            <name>jiejiebiezheyang</name>
            <email>https://gitee.com/jiejiebiezheyang</email>
            <organization>byte pulse</organization>
            <organizationUrl>https://gitee.com/byte-pulse</organizationUrl>
            <roles>
                <role>Project Lead</role>
            </roles>
            <timezone>+8</timezone>
        </developer>
    </developers>
    <modules>
        <module>bp-repository</module>
        <module>bp-common</module>
        <module>bp-infrastructure</module>
        <module>bp-web</module>
        <module>bp-app</module>
        <module>bp-service</module>
        <module>bp-security</module>
    </modules>

    <packaging>pom</packaging>

    <!-- 配置 -->
    <properties>
        <skipTests>true</skipTests>
        <java.version>25</java.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.compiler.parameters>true</maven.compiler.parameters>
        <!-- 依赖版本管理 -->
        <!--项目版本-->
        <bp.version>0.0.1</bp.version>
        <spring-boot.version>4.1.1</spring-boot.version>
        <versions-maven-plugin.version>2.21.0</versions-maven-plugin.version>
        <druid.version>1.2.28</druid.version>
        <mybatis-plus.version>3.5.17</mybatis-plus.version>
        <mybatis-plus-dynamic.version>4.5.0</mybatis-plus-dynamic.version>
        <pagehelper.version>4.1.1</pagehelper.version>
        <springdoc.version>3.1.0</springdoc.version>
        <fastjson2.version>2.0.65</fastjson2.version>
        <json-masker.version>1.1.4</json-masker.version>
        <minio.version>9.0.3</minio.version>
        <tika.version>4.0.0</tika.version>
        <okhttp.version>5.5.0</okhttp.version>
        <unirest.version>4.10.1</unirest.version>
        <hutool-captcha.version>5.8.44</hutool-captcha.version>
        <jjwt.version>0.13.0</jjwt.version>
    </properties>

    <!-- 依赖管理 -->
    <dependencyManagement>
        <dependencies>
            <!-- 项目模块 -->
            <dependency>
                <groupId>cloud.bytepulse</groupId>
                <artifactId>bp-app</artifactId>
                <version>${bp.version}</version>
            </dependency>
            <!-- common -->
            <dependency>
                <groupId>cloud.bytepulse</groupId>
                <artifactId>bp-common</artifactId>
                <version>${bp.version}</version>
            </dependency>
            <dependency>
                <groupId>cloud.bytepulse</groupId>
                <artifactId>bp-common-core</artifactId>
                <version>${bp.version}</version>
            </dependency>
            <!-- 基础设施 -->
            <dependency>
                <groupId>cloud.bytepulse</groupId>
                <artifactId>bp-infrastructure</artifactId>
                <version>${bp.version}</version>
            </dependency>
            <dependency>
                <groupId>cloud.bytepulse</groupId>
                <artifactId>bp-cache</artifactId>
                <version>${bp.version}</version>
            </dependency>
            <dependency>
                <groupId>cloud.bytepulse</groupId>
                <artifactId>bp-mq</artifactId>
                <version>${bp.version}</version>
            </dependency>
            <dependency>
                <groupId>cloud.bytepulse</groupId>
                <artifactId>bp-storage</artifactId>
                <version>${bp.version}</version>
            </dependency>
            <!-- 数据访问层 -->
            <dependency>
                <groupId>cloud.bytepulse</groupId>
                <artifactId>bp-repository</artifactId>
                <version>${bp.version}</version>
            </dependency>
            <!-- 服务层 -->
            <dependency>
                <groupId>cloud.bytepulse</groupId>
                <artifactId>bp-service</artifactId>
                <version>${bp.version}</version>
            </dependency>
            <!-- 安全层 -->
            <dependency>
                <groupId>cloud.bytepulse</groupId>
                <artifactId>bp-security</artifactId>
                <version>${bp.version}</version>
            </dependency>
            <!-- 访问层 -->
            <dependency>
                <groupId>cloud.bytepulse</groupId>
                <artifactId>bp-web</artifactId>
                <version>${bp.version}</version>
            </dependency>

            <!-- Spring Boot 4 BOM -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- 剔除默认日志实现 -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter</artifactId>
                <version>${spring-boot.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-starter-logging</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

            <!-- 数据库连接池 -->
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-4-starter</artifactId>
                <version>${druid.version}</version>
            </dependency>
            <!-- mybatis-plus -->
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot4-starter</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>
            <!-- 动态数据源 -->
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>dynamic-datasource-spring-boot4-starter</artifactId>
                <version>${mybatis-plus-dynamic.version}</version>
            </dependency>
            <!-- 分页插件 -->
            <dependency>
                <groupId>com.github.pagehelper</groupId>
                <artifactId>pagehelper-spring-boot-starter</artifactId>
                <version>${pagehelper.version}</version>
            </dependency>

            <!-- 文档生成 swagger -->
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-api</artifactId>
                <version>${springdoc.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                <version>${springdoc.version}</version>
            </dependency>
            <!-- fastjson2 -->
            <dependency>
                <groupId>com.alibaba.fastjson2</groupId>
                <artifactId>fastjson2</artifactId>
                <version>${fastjson2.version}</version>
            </dependency>
            <!-- json 脱敏 -->
            <dependency>
                <groupId>dev.blaauwendraad</groupId>
                <artifactId>json-masker</artifactId>
                <version>${json-masker.version}</version>
            </dependency>
            <!-- minio -->
            <dependency>
                <groupId>io.minio</groupId>
                <artifactId>minio</artifactId>
                <version>${minio.version}</version>
            </dependency>
            <!-- 文件 content-type 识别 -->
            <dependency>
                <groupId>org.apache.tika</groupId>
                <artifactId>tika-core</artifactId>
                <version>${tika.version}</version>
            </dependency>
            <!-- http 请求 -->
            <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>okhttp</artifactId>
                <version>${okhttp.version}</version>
            </dependency>
            <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>okhttp-jvm</artifactId>
                <version>${okhttp.version}</version>
            </dependency>
            <!-- unirest -->
            <dependency>
                <groupId>com.konghq</groupId>
                <artifactId>unirest-java-core</artifactId>
                <version>${unirest.version}</version>
            </dependency>
            <dependency>
                <groupId>com.konghq</groupId>
                <artifactId>unirest-modules-jackson</artifactId>
                <version>${unirest.version}</version>
            </dependency>

            <!-- 验证码 -->
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-captcha</artifactId>
                <version>${hutool-captcha.version}</version>
            </dependency>

            <!-- jjwt -->
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-api</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-impl</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-jackson</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
    </dependencies>

    <!-- 多配置 -->
    <profiles>
        <!-- 开发环境 -->
        <profile>
            <id>dev</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <spring.profiles.active>dev</spring.profiles.active>
                <skipTests>true</skipTests>
            </properties>
        </profile>
        <!-- 测试环境 -->
        <profile>
            <id>test</id>
            <properties>
                <spring.profiles.active>test</spring.profiles.active>
                <skipTests>true</skipTests>
            </properties>
        </profile>
        <!-- 生产环境 -->
        <profile>
            <id>prod</id>
            <properties>
                <spring.profiles.active>prod</spring.profiles.active>
                <skipTests>true</skipTests>
            </properties>
        </profile>
    </profiles>

    <!-- 构建 -->
    <build>
        <!-- 资源文件路径 -->
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>**/*.yaml</include>
                    <include>**/*.txt</include>
                    <include>**/*.xml</include>
                </includes>
            </resource>
        </resources>
        <pluginManagement>
            <!-- 插件 -->
            <plugins>
                <!-- Spring Boot Maven 插件 -->
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>4.1.1</version>
                </plugin>
                <!-- 核心插件版本管理 -->
                <!-- Maven 编译插件 -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.16.0</version>
                    <executions>
                        <!-- 默认编译 -->
                        <execution>
                            <id>default-compile</id>
                            <phase>compile</phase>
                            <goals>
                                <goal>compile</goal>
                            </goals>
                            <configuration>
                                <!-- 手动指定 lombok -->
                                <annotationProcessorPaths>
                                    <path>
                                        <groupId>org.projectlombok</groupId>
                                        <artifactId>lombok</artifactId>
                                    </path>
                                </annotationProcessorPaths>
                            </configuration>
                        </execution>
                        <!-- 测试编译 -->
                        <execution>
                            <id>default-testCompile</id>
                            <phase>test-compile</phase>
                            <goals>
                                <goal>testCompile</goal>
                            </goals>
                            <configuration>
                                <!-- 手动指定 lombok -->
                                <annotationProcessorPaths>
                                    <path>
                                        <groupId>org.projectlombok</groupId>
                                        <artifactId>lombok</artifactId>
                                    </path>
                                </annotationProcessorPaths>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-clean-plugin</artifactId>
                    <version>3.5.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>3.5.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>3.5.1</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-install-plugin</artifactId>
                    <version>3.1.4</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-deploy-plugin</artifactId>
                    <version>3.1.4</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.6.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-site-plugin</artifactId>
                    <version>4.0.0-M16</version>
                </plugin>
            </plugins>
        </pluginManagement>

        <!-- 插件 -->
        <plugins>
            <plugin>
                <!-- 版本管理插件 -->
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <version>${versions-maven-plugin.version}</version>
                <configuration>
                    <!-- 不生成备份POM -->
                    <generateBackupPoms>false</generateBackupPoms>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
