# 生产环境配置
spring:
  datasource:
    dynamic:
      primary: master
      strict: true
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/master_prod?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: passwd
          driverClassName: com.mysql.cj.jdbc.Driver
  #        slave:
  #          url: jdbc:mysql://127.0.0.1:3306/slave_prod?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
  #          username: root
  #          password: passwd
  #          driverClassName: com.mysql.cj.jdbc.Driver
  data:
    # redis配置
    redis:
      # 地址
      host: 127.0.0.1
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# 关闭 swagger
springdoc:
  api-docs:
    enabled: false

app:
  login:
    # 登陆无操作多久, 登陆失效 (单位: 分钟) 0 表示不过期
    expiration-minutes: 30
  # minio 配置
  minio:
    endpoint: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket-name: quickly-prod
  # redis 配置
  redis:
    prefix: "bp:"
  # 提供的第三方接口配置本地加密密钥(用于加密用户的密钥)
  external-api:
    secretKey: rcII2vlKYg1Fw2NvmZZg4570UwLSkYRE+yOZRCU9aTk=
    iv: xVOqDSMzgI3ZFL68TJ21BA==
  captcha:
    expiration-seconds: 30
